
services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5173:5173"       
    volumes:
    - ./frontend/event_tick_frontend:/src
    depends_on:
      - backend
    command: npm run dev

volumes:
  postgres_data:


  